---
name: Lint and Test
'on': workflow_call

permissions:
  contents: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  gotest:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: run tests
        run: go test ./... -coverprofile=./cover.out
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/ajgon/envdir
          threshold-file: 90
          threshold-package: 90
          threshold-total: 90

          git-token: ${{ github.ref_name == 'master' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
