---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: On push and pull request
'on':
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write

jobs:
  lint-test:
    uses: ajgon/envdir/.github/workflows/lint-and-test.yaml@master
